dist: xenial
language: node_js
node_js:
    #ยง '- "' + data.config.npm.node.version + '"'
    - "10.12"

jobs:
    include:
        - stage: compile
          if: type = push
          script: ./scripts/travis-release.sh
        - stage: compile
          if: type = pull_request
          script:
              - npm install
              - npm run test
              - npm run verify

script:
