dist: xenial
language: node_js
# node_js: # node version is specified in .nvmrc

install:
  - npm ci

script:
  - npm run build
  - npm run test
  - npm run verify

jobs:
    include:
        - stage: compile
          if: type = push AND commit_message !~ /(-skipci)/
          script: ./scripts/travis-release.sh
        - stage: compile
          if: type = pull_request
          script:
              - npm install
              - npm run test
              - npm run verify

script:
